vim.keymap.set({ 'n', 'v' }, '<Space>', '<Nop>', { silent = true })
vim.keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
vim.keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
vim.keymap.set('n', '<leader>i', ':silent %!prettier --stdin-filepath %<CR>')
vim.keymap.set('n', '<M-j>', 'jzz')
vim.keymap.set('n', '<M-k>', 'kzz')
